name: ${COMPOSE_PROJECT_NAME:-max}

services:
  # -------------------------------------------------------------------------------------
  # web-server SERVICE
  # -------------------------------------------------------------------------------------
  web-server:
    image: web-server-prod
    build:
      target: prod
      # Context & Dockerfile is set to services/web-server in docker-compose.yaml
    command: ["python", "-m", "uvicorn", "src.main:app","--reload", "--log-level", "${WEB_LOG_LEVEL:-warning}"]

  # -------------------------------------------------------------------------------------
  # STT SERVICE
  # -------------------------------------------------------------------------------------
  stt:
    image: stt-prod
    build:
      target: prod
      # Context is set to services/max-stt in docker-compose.yaml
      dockerfile: Dockerfile
    # ports are not exposed
    restart: unless-stopped
    command: ["python", "-m", "uvicorn", "src.app:app","--reload","--log-level", "${STT_LOG_LEVEL:-warning}"]

    # -------------------------------------------------------------------------------------
    # ASSISTANT SERVICE
    # -------------------------------------------------------------------------------------
  assistant:
    image: assistant-prod
    build:
      target: prod
    command: [
      "python", "-m", "uvicorn", "src.main:app",
      "--reload",
      "--log-config", "src/log_config.json",
      "--log-level", "${ASSISTANT_LOG_LEVEL:-warning}"
    ]

  # -------------------------------------------------------------------------------------
  # ollama SERVICE
  # -------------------------------------------------------------------------------------
  # common image

  # -------------------------------------------------------------------------------------
  # proxy SERVICE
  # -------------------------------------------------------------------------------------
  proxy:
    ports:
      - "${PROXY_HTTP_PORT:-80}:80"
      - "${PROXY_HTTPS_PORT:-9443}:443"
    volumes:
      # mount a replacement nginx.cong to set workers to 1
      - ./proxy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the production template
      - ./proxy/nginx/prod.conf.template:/etc/nginx/templates/default.conf.template:ro
      # Mount your SSL certificates (obtained via Certbot or another provider)
      - /etc/letsencrypt:/etc/letsencrypt:ro


