name: ${COMPOSE_PROJECT_NAME:-max}-prod
services:
  stt:
    image: stt-prod:latest
    build:
      target: prod
      # Context is set to services/max-stt in docker-compose.yaml
      dockerfile: Dockerfile
    # ports are not exposed
    restart: unless-stopped
    command: ["python", "-m", "src.app"]


  proxy:
    ports:
      - "${PROD_PROXY_HTTP_PORT:-80}:80"
      - "${PROD_PROXY_HTTPS_PORT:-443}:443"
    volumes:
      # Mount the production template
      - ./proxy/nginx/prod.conf.template:/etc/nginx/templates/default.conf.template:ro
      # Mount your SSL certificates (obtained via Certbot or another provider)
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - stt
    environment:
      # Define the variables used in the template
      - UPSTREAM_HOST=${UPSTREAM_HOST:-stt}
      - UPSTREAM_PORT=${UPSTREAM_PORT:-8765}
      - SERVER_NAME=${PROD_SERVER_NAME:-your-domain.com} # <-- IMPORTANT: Change this in your .env file

