# docker-compose.shared.yaml
name: shared-services
services:
  # -------------------------------------------------------------------------------------
  # Ollama SERVICE
  # -------------------------------------------------------------------------------------
  ollama:
    container_name: ollama-gpu
    profiles: ["container-ollama"]
    build:
      context: ./services/ollama
      dockerfile: Dockerfile
    image: ollama-gpu
    networks:
      - ai-shared-network
    # Alternative official ollama image
    # image: ollama/ollama:latest
    restart: unless-stopped
    user: "1000:1000"
    environment:
      - OLLAMA_KEEP_ALIVE=-1
      - DEBUG=${OLLAMA_DEBUG:-0}
    # Needed if using official ollama image
    #  - OLLAMA_MODELS=/home/ollama/.ollama
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: nvidia
#              count: all
#              capabilities: [ gpu ]
    ports:
      - "127.0.0.1:11434:11434"
    volumes:
      # Mount the named volume to the NEW non-root user's models directory
      - ollama_models:/home/ollama/.ollama
    healthcheck:
      # Check if the Ollama API is responding.
      test: [ "CMD", "curl", "-f", "http://localhost:11434" ]
      interval: 120s
      timeout: 15s
      retries: 3
      start_period: 240s

volumes:
  ollama_models:
    external: true

networks:
  ai-shared-network:
    external: true          # Tells Docker this network already exists