name: ${COMPOSE_PROJECT_NAME:-max}
services:
  stt:
    image: stt-prod:latest
    build:
      target: prod
      # Context is set to services/max-stt in docker-compose.yaml
      dockerfile: Dockerfile
    # ports are not exposed
    restart: unless-stopped



  proxy:
    ports:
      - "${PROD_PROXY_HTTP_PORT:-80}:80"
      - "${PROD_PROXY_HTTPS_PORT:-443}:443"
    volumes:
      # mount a replacement nginx.cong to set workers to 1
      - ./proxy/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # Mount the production template
      - ./proxy/nginx/prod.conf.template:/etc/nginx/templates/default.conf.template:ro
      # Mount your SSL certificates (obtained via Certbot or another provider)
      - /etc/letsencrypt:/etc/letsencrypt:ro


